### ISSUE TITLE
Building via docker-update.sh fails

### ISSUE THREAD

**Issue by wortkrieg** [astuto/astuto#127] opened 2022-07-04 13:22 UTC
The error is:
 => ERROR [ 4/12] RUN npm install -g yarn 

After fiddling around, I found that in dockerfile:
`RUN apt-get update -qq && apt-get install -y nodejs npm postgresql-client`

npm has to be installed  explicitly to work correctly. Currently it just installs nodejs and postgresql. 
Maybe consider fixing this if others are affected, too.

**Comment by riggraz** [comment] 2022-07-05 16:18
Hi! I've never encountered this problem: actually, npm should be shipped inside nodejs by default. Are you up to date with the latest commit in `main` branch or did you make any custom changes to the Dockerfile or docker-compose?

Anyway, even though I'm not able to reproduce it,  I'll leave the issue open for a while to see if someone else has the same problem. Thanks for taking the time to open an issue!

**Comment by wortkrieg** [comment] 2022-07-06 07:33
Hi there,
No changes at all, just cloned the repo as-is and tried spinning it up to a clean system (also fresh docker installation), but didn't work due to the npm missing problem.

**Comment by riggraz** [comment] 2022-07-14 16:19
I'll make some tests and let you know. If adding npm to `apt-get install` doesn't break the installation process for me or other users, then it only makes sense to add it, just in case someone else encounters the same problem as you.

**Comment by riggraz** [comment] 2022-07-16 11:16
Hi @wortkrieg , can you give me additional information about your operating system and docker version?

I tried adding npm to apt-get install, but I get the following error:

![Screenshot 2022-07-16 at 13 07 34](https://user-images.githubusercontent.com/31478034/179352585-c7bded42-ceff-4eb9-aa2f-4a2d324e6b94.png)

I am on macOS 12.3.1 running Docker Desktop 4.8.1 (Docker engine 20.10.14, docker compose 1.29.2)

**Comment by wortkrieg** [comment] 2022-07-16 11:34
Hi there,
I tried ands succeeded on macOS 12.4 running the recent docker desktop (I can't tell the exact version in the moment as I don't have the machine at hand. If required I can do so on monday). 
I also tried and succeeded on a clean vm running Debian 11, just using the line above. Using the Dockerfile without npm did result in an error. Very intersting. I'll check out the missing version information on the host and let you know.

**Comment by riggraz** [comment] 2022-09-15 15:43
Hi wortkrieg 👋🏻 just wanted to say that we changed quite a lot of the installation process, so if you're still interested, you may want to follow the new instructions in the README of the repo and see if everything works without fiddling around with the Dockerfile.

In the new installation instructions, if you just want to deploy an instance of Astuto to production, you won't build your own Docker image but instead pull the existing one from Docker Hub. It'd be interesting to see if the image from Docker Hub gives you the same error about npm not being installed.

**Comment by riggraz** [comment] 2023-04-16 19:17
Closing this issue because it's very old and without new updates!

**Closed by riggraz** 2023-04-16 19:17 UTC
Labels: bug
