### ISSUE TITLE
Adding a comment results in 500

### ISSUE THREAD

**Issue by andrejsoucek** [astuto/astuto#387] opened 2024-07-24 14:15 UTC
After posting a comment, 500 Internal Server Error occurs. The comment is however correctly added and visible after the page refresh.
`EMAIL_DELIVERY_METHOD` env var is not defined, I don't want to send any emails.

The post is published anonymously so maybe the `if comment.user.id != user.id` fails here: https://github.com/astuto/astuto/blob/97eb40f0c61bf2e0507b7cbc0ae7207e3199f870/app/workflows/send_notification_for_comment_workflow.rb#L19
```
I, [2024-07-24T14:02:03.958390 #33]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [9f9f2880-e95a-4237-90be-34dcb65cd754] Performed ActionMailer::MailDeliveryJob (Job ID: 9f9f2880-e95a-4237-90be-34dcb65cd754) from Async(mailers) in 37.51ms
I, [2024-07-24T14:02:08.402618 #33]  INFO -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22] Started POST "/posts/3/comments" for 100.64.1.22 at 2024-07-24 14:02:08 +0000
I, [2024-07-24T14:02:08.403787 #33]  INFO -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22] Processing by CommentsController#create as JSON
I, [2024-07-24T14:02:08.403861 #33]  INFO -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   Parameters: {"comment"=>{"body"=>"huh", "parent_id"=>nil, "is_post_update"=>false}, "post_id"=>"3"}
D, [2024-07-24T14:02:08.407589 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   Tenant Load (1.2ms)  SELECT "tenants".* FROM "tenants" ORDER BY "tenants"."id" ASC LIMIT $1  [["LIMIT", 1]]
D, [2024-07-24T14:02:08.410219 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   TenantSetting Load (1.2ms)  SELECT "tenant_settings".* FROM "tenant_settings" WHERE "tenant_settings"."tenant_id" = $1 ORDER BY "tenant_settings"."id" ASC LIMIT $2  [["tenant_id", 1], ["LIMIT", 1]]
D, [2024-07-24T14:02:08.412548 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   TenantBilling Load (1.0ms)  SELECT "tenant_billings".* FROM "tenant_billings" WHERE "tenant_billings"."tenant_id" = $1 ORDER BY "tenant_billings"."id" ASC LIMIT $2  [["tenant_id", 1], ["LIMIT", 1]]
D, [2024-07-24T14:02:08.416248 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   User Load (1.2ms)  SELECT "users".* FROM "users" WHERE "users"."tenant_id" = $1 AND "users"."id" = $2 ORDER BY "users"."id" ASC LIMIT $3  [["tenant_id", 1], ["id", 3], ["LIMIT", 1]]
D, [2024-07-24T14:02:08.418799 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   TenantBilling Load (0.9ms)  SELECT "tenant_billings".* FROM "tenant_billings" WHERE "tenant_billings"."tenant_id" = $1 LIMIT $2  [["tenant_id", 1], ["LIMIT", 1]]
D, [2024-07-24T14:02:08.422235 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   TRANSACTION (0.9ms)  BEGIN
D, [2024-07-24T14:02:08.423538 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."tenant_id" = $1 AND "users"."id" = $2 LIMIT $3  [["tenant_id", 1], ["id", 3], ["LIMIT", 1]]
D, [2024-07-24T14:02:08.425953 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   Post Load (1.0ms)  SELECT "posts".* FROM "posts" WHERE "posts"."tenant_id" = $1 AND "posts"."id" = $2 LIMIT $3  [["tenant_id", 1], ["id", 3], ["LIMIT", 1]]
D, [2024-07-24T14:02:08.429202 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   Comment Create (1.7ms)  INSERT INTO "comments" ("body", "user_id", "post_id", "created_at", "updated_at", "tenant_id") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["body", "huh"], ["user_id", 3], ["post_id", 3], ["created_at", "2024-07-24 14:02:08.426515"], ["updated_at", "2024-07-24 14:02:08.426515"], ["tenant_id", 1]]
D, [2024-07-24T14:02:08.432112 #33] DEBUG -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   TRANSACTION (2.5ms)  COMMIT
I, [2024-07-24T14:02:08.433546 #33]  INFO -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22] Completed 500 Internal Server Error in 30ms (ActiveRecord: 12.9ms | Allocations: 4436)
F, [2024-07-24T14:02:08.434135 #33] FATAL -- : [b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   
[b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22] NoMethodError (undefined method `id' for nil:NilClass):
[b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22]   
[b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22] app/workflows/send_notification_for_comment_workflow.rb:19:in `run'
[b880ba5d532f04079bdb1c209e6184bd] [https://example.com/posts/3/comments] [100.64.1.22] app/controllers/comments_controller.rb:30:in `create'

```

**Comment by riggraz** [comment] 2024-07-24 15:44
Hi, thanks for reporting the issue!

I think this only happens if you comment anonymous feedback, but not if you comment non-anonymous feedback. Can you confirm this?

(The problem is that Astuto is trying to send an email to the author of the comment, but there is no author for anonymous feedback!)

**Comment by andrejsoucek** [comment] 2024-07-25 07:19
Yes, I can confirm and that was my assumption aswell. :)

**Comment by riggraz** [comment] 2024-07-25 15:54
The bug should be fixed with the latest commit :)

**Closed** 2024-07-25 15:54 UTC
Labels: bug
